---
- name: Generate sr-list
  set_fact:
    sr_list: "{{ sr_list + [ {'name': item.key, 'uuid': item.value.uuid} ] }}"
  with_dict: "{{ storage }}"

- include: vm_backup.yml
  with_items: "{{ vm }}"
  loop_control:
    loop_var: item_vm
